In [1]:
corpus = [
    'Linux has been around since the mid-1990s.',
    'Linux distributions include the Linux kernel.',
    'Linux is one of the most prominent open-source software.'
]

corpus

['Linux has been around since the mid-1990s.',
 'Linux distributions include the Linux kernel.',
 'Linux is one of the most prominent open-source software.']

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
vectorized_X = vectorizer.fit_transform(corpus).todense()
vectorized_X

matrix([[1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1],
        [0, 0, 0, 1, 0, 1, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1]])

In [6]:
vectorizer.get_feature_names_out()

array(['1990s', 'around', 'been', 'distributions', 'has', 'include', 'is',
       'kernel', 'linux', 'mid', 'most', 'of', 'one', 'open', 'prominent',
       'since', 'software', 'source', 'the'], dtype=object)

In [5]:
import numpy as np
from sklearn.metrics.pairwise import euclidean_distances

for i in range(len(vectorized_X)):
    for j in range(i, len(vectorized_X)):
        if i == j:
            continue
        
        vec_i = np.asarray(vectorized_X[i])
        vec_j = np.asarray(vectorized_X[j])
        
        jarak = euclidean_distances(vec_i, vec_j)
        print(f'Jarak dokumen {i+1} dan {j+1}: {jarak}')

Jarak dokumen 1 dan 2: [[3.16227766]]
Jarak dokumen 1 dan 3: [[3.74165739]]
Jarak dokumen 2 dan 3: [[3.46410162]]


In [7]:
corpus

['Linux has been around since the mid-1990s.',
 'Linux distributions include the Linux kernel.',
 'Linux is one of the most prominent open-source software.']

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(stop_words='english')
vectorized_X = vectorizer.fit_transform(corpus).todense()
vectorized_X

matrix([[1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
        [0, 1, 1, 1, 2, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 1, 1, 1, 1]])

In [10]:
vectorizer.get_feature_names_out()

array(['1990s', 'distributions', 'include', 'kernel', 'linux', 'mid',
       'open', 'prominent', 'software', 'source'], dtype=object)

In [11]:
corpus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story'
]

corpus

['the house had a tiny little mouse',
 'the cat saw the mouse',
 'the mouse ran away from the house',
 'the cat finally ate the mouse',
 'the end of the mouse story']

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english')
response = vectorizer.fit_transform(corpus)
print(response)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 18 stored elements and shape (5, 12)>
  Coords	Values
  (0, 5)	0.47557510189256375
  (0, 11)	0.5894630806320427
  (0, 6)	0.5894630806320427
  (0, 7)	0.2808823162882302
  (1, 7)	0.3477147117091919
  (1, 2)	0.5887321837696324
  (1, 9)	0.7297183669435993
  (2, 5)	0.47557510189256375
  (2, 7)	0.2808823162882302
  (2, 8)	0.5894630806320427
  (2, 1)	0.5894630806320427
  (3, 7)	0.2808823162882302
  (3, 2)	0.47557510189256375
  (3, 4)	0.5894630806320427
  (3, 0)	0.5894630806320427
  (4, 7)	0.3193023297639811
  (4, 3)	0.6700917930430479
  (4, 10)	0.6700917930430479


In [13]:
vectorizer.get_feature_names_out()

array(['ate', 'away', 'cat', 'end', 'finally', 'house', 'little', 'mouse',
       'ran', 'saw', 'story', 'tiny'], dtype=object)

In [14]:
response.todense()

matrix([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.4755751 , 0.58946308, 0.28088232, 0.        , 0.        ,
         0.        , 0.58946308],
        [0.        , 0.        , 0.58873218, 0.        , 0.        ,
         0.        , 0.        , 0.34771471, 0.        , 0.72971837,
         0.        , 0.        ],
        [0.        , 0.58946308, 0.        , 0.        , 0.        ,
         0.4755751 , 0.        , 0.28088232, 0.58946308, 0.        ,
         0.        , 0.        ],
        [0.58946308, 0.        , 0.4755751 , 0.        , 0.58946308,
         0.        , 0.        , 0.28088232, 0.        , 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.67009179, 0.        ,
         0.        , 0.        , 0.31930233, 0.        , 0.        ,
         0.67009179, 0.        ]])

In [17]:
import pandas as pd

df = pd.DataFrame(response.todense().T,
                 index=vectorizer.get_feature_names_out(),  # Changed from get_feature_names() to get_feature_names_out()
                 columns=[f'D{i+1}' for i in range(len(corpus))])
df

,D1,D2,D3,D4,D5
ate,0.000000,0.000000,0.000000,0.589463,0.000000
away,0.000000,0.000000,0.589463,0.000000,0.000000
cat,0.000000,0.588732,0.000000,0.475575,0.000000
end,0.000000,0.000000,0.000000,0.000000,0.670092
finally,0.000000,0.000000,0.000000,0.589463,0.000000
house,0.475575,0.000000,0.475575,0.000000,0.000000
little,0.589463,0.000000,0.000000,0.000000,0.000000
mouse,0.280882,0.347715,0.280882,0.280882,0.319302
ran,0.000000,0.000000,0.589463,0.000000,0.000000
saw,0.000000,0.729718,0.000000,0.000000,0.000000
